import{S as l}from"./assets/vendor-338edac8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();function u(){c.innerHTML='<span class="loader"></span>'}function p(s){let t="";s.hits.forEach(o=>{t+=`<div class="gallery-card">
                <a href="${o.largeImageURL}"><img src="${o.webformatURL}" width="360px" alt="${o.tags}"></a>
                <ul class="card-list">
                    <li><p>Likes:</p><p>${o.likes}</p></li>
                    <li><p>Views:</p><p>${o.views}</p></li>
                    <li><p>Comments:</p><p>${o.comments}</p></li>
                    <li><p>Downloads:</p><p>${o.downloads}</p></li>
                </ul>
            </div>`}),c.innerHTML=t,new l(".gallery-card a",{captionsData:"alt",captionDelay:250}).refresh()}function f(){const s=new URLSearchParams({key:"44001471-3db462177f0e91bc0a7989cfe",q:n.value,image_type:"photo",orientation:"horizontal",safesearch:"safe"});fetch(`https://pixabay.com/api/?${s}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()}).then(t=>{p(t)}).catch(t=>{console.log(t)})}const c=document.querySelector(".gallery"),d=document.querySelector(".search-bar"),n=document.querySelector(".search-bar input");d.addEventListener("submit",s=>{s.preventDefault(),!(n.value==""||n.value==" ")&&(u(),f(),s.currentTarget.reset())});
//# sourceMappingURL=commonHelpers.js.map
