import{S as p,i as c}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function e(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(r){if(r.ep)return;r.ep=!0;const t=e(r);fetch(r.href,t)}})();const l=document.querySelector(".gallery"),u=document.querySelector(".search-bar"),s=document.querySelector(".search-bar input");function f(){l.innerHTML='<span class="loader"></span>'}function d(a){let o="";a.hits.forEach(e=>{o+=`<div class="gallery-card">
                <a href="${e.largeImageURL}"><img src="${e.webformatURL}" width="360px" alt="${e.tags}"></a>
                <ul class="card-list">
                    <li><p>Likes:</p><p>${e.likes}</p></li>
                    <li><p>Views:</p><p>${e.views}</p></li>
                    <li><p>Comments:</p><p>${e.comments}</p></li>
                    <li><p>Downloads:</p><p>${e.downloads}</p></li>
                </ul>
            </div>`}),l.innerHTML=o,new p(".gallery-card a",{captionsData:"alt",captionDelay:250}).refresh()}u.addEventListener("submit",a=>{if(a.preventDefault(),s.value==""||s.value==" "){c.error({position:"topRight",message:"Search bar is empty!"});return}f();const o=new URLSearchParams({key:"44001471-3db462177f0e91bc0a7989cfe",q:s.value,image_type:"photo",orientation:"horizontal",safesearch:"safe"});fetch(`https://pixabay.com/api/?${o}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{e.hits.length==0&&c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),d(e)}).catch(e=>{console.log(e)}),a.currentTarget.reset()});
//# sourceMappingURL=commonHelpers.js.map
