import{S as p,i as c}from"./assets/vendor-0fc460d7.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function e(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(r){if(r.ep)return;r.ep=!0;const t=e(r);fetch(r.href,t)}})();const l=document.querySelector(".gallery"),u=document.querySelector(".search-bar"),s=document.querySelector(".search-bar input");new p(".gallery-card a",{});function d(){l.innerHTML="<p>Loading images, please wait...</p>"}function f(o){let i="";o.hits.forEach(e=>{i+=`<div class="gallery-card">
                <a href="${e.largeImageURL}"><img src="${e.webformatURL}" width="360px" alt="${e.tags}"></a>
                <ul class="card-list">
                    <li><p>Likes:</p><p>${e.likes}</p></li>
                    <li><p>Views:</p><p>${e.views}</p></li>
                    <li><p>Comments:</p><p>${e.comments}</p></li>
                    <li><p>Downloads:</p><p>${e.downloads}</p></li>
                </ul>
            </div>`}),l.innerHTML=i}u.addEventListener("submit",o=>{if(o.preventDefault(),s.value==""||s.value==" "){c.error({position:"topRight",message:"Search bar is empty!"});return}d();const i=new URLSearchParams({key:"44001471-3db462177f0e91bc0a7989cfe",q:s.value,image_type:"photo",orientation:"horizontal",safesearch:"safe"});fetch(`https://pixabay.com/api/?${i}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{e.hits.length==0&&c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),f(e)}).catch(e=>{console.log(e)})});
//# sourceMappingURL=commonHelpers.js.map
